image: microsoft/dotnet:1.1-sdk
pipelines:
  default:
    - step:
        script:
          # Generate build number
          - BUILD_NUMBER=`hg id -i`
          - echo "Build number':' ${BUILD_NUMBER}"
          # Restore packages
          - dotnet restore
          # Build project
          - dotnet build
          # Run tests
          # - dotnet test test/Kissinjer.Tests/Kissinjer.Tests.csproj
          # Create package
          - dotnet pack --configuration ${BUILD_CONFIGURATION} --version-suffix=beta-$BUILD_NUMBER src/Kissinjer/Kissinjer.csproj
          # Push generated package(s)
          - "for file in src/Kissinjer/bin/${BUILD_CONFIGURATION}/*.nupkg; do dotnet nuget push $file -k ${NUGET_APIKEY}; done"